FROM debian:buster-slim

LABEL maintainer="R3GISTRY"
LABEL description="Sync in Docker."

WORKDIR /tmp/

ADD \
https://download-cdn.resilio.com/2.5.13/linux-i386/resilio-sync_i386.tar.gz \
.

RUN \
tar -xvf resilio-sync_i386.tar.gz \
&& mv rslsync /usr/bin/sync \
&& rm -r *

VOLUME ["/mnt/sync/"]

ENTRYPOINT ["sync"]
CMD ["--help"]
