FROM debian:buster-slim

LABEL maintainer="R3GISTRY"
LABEL description="Sync in Docker."

WORKDIR /tmp/

ADD \
https://download-cdn.resilio.com/2.4.5/linux-arm64/resilio-sync_arm64.tar.gz \
.

RUN \
tar -xvf resilio-sync_arm64.tar.gz \
&& mv rslsync /usr/bin/sync \
&& rm -r *

VOLUME ["/mnt/sync/"]

ENTRYPOINT ["sync"]
CMD ["--help"]
